name: Build and Deploy Blog to Github Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
          
      - name: Generate Blog
        run: make html
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: './build/html'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: blog
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3